name = "cloudflare_temp_email"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]
keep_vars = true

# routes = [
# 	{ pattern = "temp-email-api.xxxxx.xyz", custom_domain = true },
# ]

# [assets]
# directory = "../frontend/dist/"
# binding = "ASSETS"
# run_worker_first = true

# [triggers]
# crons = [ "0 0 * * *" ]

# CLEANUP_BATCH_SIZE = 3000
# send_email = [
#    { name = "SEND_MAIL" },
# ]
# SEND_MAIL_DOMAINS = ["example.com", "mail.example.com"]

[vars]
PREFIX = "tmp"
DEFAULT_DOMAINS = "${DEFAULT_DOMAINS}"
DOMAINS = "${DOMAINS}"
JWT_SECRET = "${JWT_SECRET}"
BLACK_LIST = ""
ENABLE_USER_CREATE_EMAIL = true
ENABLE_USER_DELETE_EMAIL = true
ENABLE_AUTO_REPLY = false

[[d1_databases]]
binding = "DB"
database_name = "${D1_DATABASE_NAME}"
database_id = "${D1_DATABASE_ID}"

# [ai]
# binding = "AI"

# [[kv_namespaces]]
# binding = "KV"
# id = "xxxx"

# [[unsafe.bindings]]
# name = "RATE_LIMITER"
# type = "ratelimit"
# namespace_id = "1001"
# simple = { limit = 10, period = 60 }

# [[services]]
# binding = "AUTH_INBOX"
# service = "auth-inbox"
